scene:
  
  route: [56, 32] 

  min_s: 100 
  max_s: 500 
  n_vehicles: 5 
  n_ped: 40 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
