scene:
  
  route: [60, 33] 

  min_s: 20 
  max_s: 200 
  n_vehicles: 4 
  n_ped: 40 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
