
scene:
  
  route: [67, 138] 

  min_s: -300
  max_s: 300 
  n_vehicles: 50 
  n_ped: 0 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
