scene:
  
  route: [218, 62] 

  min_s: -200 
  max_s: 200 
  n_vehicles: 25 
  n_ped: 50 

  vehicle:
    route: False
    speed: 2.0 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
