
scene:
  
  route: [127, 13] 

  min_s: 30 
  max_s: 100 
  n_vehicles: 2 
  n_ped: 40 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
