scene:
  
  route: [226, 18] 

  min_s: -300 
  max_s: 300 
  n_vehicles: 30 
  n_ped: 100 

  vehicle:
    route: False
    speed: 1.9 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
