
scene:
  
  route: [136, 134] 

  min_s: -1000 
  max_s: 1000 
  n_vehicles: 30 
  n_ped: 100 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
