scene:
  
  route: [226, 18] 

  min_s: -200 
  max_s: 200 
  n_vehicles: 13 
  n_ped: 100 

  vehicle:
    route: False
    speed: 2.0 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
