scene:
  
  route: [1, 1] 

  min_s: -300 
  max_s: 300 
  n_vehicles: 20 
  n_ped: 10 

  vehicle:
    route: False
    speed: 2.0 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
