scene:
  
  route: [65, 71] 

  min_s: -100 
  max_s: 100 
  n_vehicles: 25 
  n_ped: 100 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
  
