scene:
  
  route: [82, 82] 

  min_s: 50 
  max_s: 2000 
  n_vehicles: 15 
  n_ped: 100 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
  
