scene:
  
  route: [81, 81] 

  min_s: 20
  max_s: 400 
  n_vehicles: 7 
  n_ped: 10 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
