
scene:
  
  route: [146, 225] 

  min_s: 10 
  max_s: 60 
  n_vehicles: 4 
  n_ped: 20 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
