scene:

  route: [74, 1] 

  min_s: -1000 
  max_s: 1000 
  n_vehicles: 20 
  n_ped: 100 

  vehicle:
    route: False
    speed: 1.9
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
