
scene:

  route: [37, 17] 

  min_s: -100
  max_s: 100 
  n_vehicles: 15 
  n_ped: 100 

  vehicle:
    route: False
    speed: 2.0 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
