scene:

  route: [63, 69] 

  min_s: 30 
  max_s: 150
  n_vehicles: 7 
  n_ped: 50 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
