scene:

  route: [32, 28] 

  min_s: -500 
  max_s: 500 
  n_vehicles: 13 
  n_ped: 50 

  vehicle:
    route: False
    speed: 2.0 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9
