name: test 
seed: 1596
save: False 

map: Town01
map_config: layers_none
n_scene: 1
reload_map: False 

logdir: None

exit_after_route: True
frames: 200 

display: False
grid_size: [1,1]
window_size: [0, 0]

hero: 
  spawn_angle: 0
  bp: charger_2020
  sensors: ['rgb', 'top']
  autopilot: False
  route: front2bev
  speed: 2.0

scene:

  min_s: 100 
  max_s: 300
  n_vehicles: 5 
  n_ped: 15 

  vehicle:
    route: False
    speed: 2.1 
    autopilot: False 

  pedestrian: 
    percent_static: 0.1 
    percent_walking: 0.1
    percent_running: 0.9

rgb:
  id: rgb
  bp: sensor.camera.rgb
  location: [0.0, 0.0, 2.0]
  rotation: [0.0, 0.0, 0.0]
  params: 
    image_size_x: 1024
    image_size_y: 1024
    fov: 90.0
  save: True
 
top:
  id: bev
  bp: sensor.camera.semantic_segmentation
  location: [0.0, 0.0, 32.0]
  rotation: [-90.0, 0.0, 0.0]
  params: 
    image_size_x: 1024
    image_size_y: 1024
  save: True

traffic: 
    tm_port: 8000
    tm_hybrid: False
    seed: 1596

    spawn_traffic: False
    n_vehicles: 50
    filterv: vehicle.*
    vehicle_speed: -20.0

    n_walkers: 100
    filterw: walker.pedestrian.*
    percent_running: 0.1
    percent_crossing: 0.1

